Stuff

diff --git a/scripts.symlink/volume b/scripts.symlink/volume
--- a/scripts.symlink/volume
+++ b/scripts.symlink/volume
@@ -1,105 +1,173 @@
-#!/bin/bash
-# Displays the default device, volume, and mute status for i3blocks
+#!/usr/bin/env bash
 
-AUDIO_HIGH_SYMBOL='  '
+# Based on a script by:
+# Julien Bonjean <julien@bonjean.info>
+# Alexander Keller <github@nycroth.com>
 
-AUDIO_MED_THRESH=50
-AUDIO_MED_SYMBOL='  '
+AUDIO_HIGH_SYMBOL=''
+AUDIO_LOW_SYMBOL=''
+AUDIO_MUTED_SYMBOL=''
 
-AUDIO_LOW_THRESH=0
-AUDIO_LOW_SYMBOL='  '
+MIXER=
+SCONTROL=
 
-AUDIO_MUTED_SYMBOL='  '
-
-DEFAULT_COLOR="#ffffff"
-MUTED_COLOR="#a0a0a0"
-
-LONG_FORMAT=0
-SHORT_FORMAT=2
-USE_PERCENT=1
-
-while getopts F:f:pH:M:L:T:t:C:c:h opt; do
-    case "$opt" in
-        F) LONG_FORMAT="$OPTARG" ;;
-        f) SHORT_FORMAT="$OPTARG" ;;
-        p) USE_PERCENT=0 ;;
-        H) AUDIO_HIGH_SYMBOL="$OPTARG" ;;
-        M) AUDIO_MED_SYMBOL="$OPTARG" ;;
-        L) AUDIO_LOW_SYMBOL="$OPTARG" ;;
-        X) AUDIO_MUTED_SYMBOL="$OPTARG" ;;
-        T) AUDIO_MED_THRESH="$OPTARG" ;;
-        t) AUDIO_LOW_THRESH="$OPTARG" ;;
-        C) DEFAULT_COLOR="$OPTARG" ;;
-        c) MUTED_COLOR="$OPTARG" ;;
-        h) printf \
-"Usage: volume-pulseaudio [-F format] [-f format] [-p] [-H symb] [-M symb]
-        [-L symb] [-X symb] [-T thresh] [-t thresh] [-C color] [-c color] [-h]
-Options:
--F, -f\tOutput format (-F long format, -f short format) to use, amonst:
-\t0\t symb vol [index:name]\t (default long)
-\t1\t symb vol [name]
-\t2\t symb vol [index]\t (default short)
-\t3\t symb vol
--p\tOmit the percent sign (%%) in volume
--H\tSymbol to use when audio level is high. Default: '$AUDIO_HIGH_SYMBOL'
--M\tSymbol to use when audio level is medium. Default: '$AUDIO_MED_SYMBOL'
--L\tSymbol to use when audio level is low. Default: '$AUDIO_LOW_SYMBOL'
--X\tSymbol to use when audio is muted. Default: '$AUDIO_MUTED_SYMBOL'
--T\tThreshold for medium audio level. Default: $AUDIO_MED_THRESH
--t\tThreshold for low audio level. Default: $AUDIO_LOW_THRESH
--C\tColor for non-muted audio. Default: $DEFAULT_COLOR
--c\tColor for muted audio. Default: $MUTED_COLOR
--h\tShow this help text
-" && exit 0;;
-    esac
-done
-
-function set_default_playback_device_next {
-    inc=${1:-1}
-    num_devices=$(pacmd list-sinks | grep -c index:)
-    sink_arr=($(pacmd list-sinks | grep index: | grep -o '[0-9]\+'))
-    default_sink_index=$(( $(pacmd list-sinks | grep index: | grep -no '*' | grep -o '^[0-9]\+') - 1 ))
-    default_sink_index=$(( ($default_sink_index + $num_devices + $inc) % $num_devices ))
-    default_sink=${sink_arr[$default_sink_index]}
-    pacmd set-default-sink $default_sink
+usage() {
+cat <<EOF
+usage: $(basename $0) [-h] [-m mixer] [-c control] [toggle] [up %] [down %] [print] [i3blocks]
+  general:
+    -h, --help      print this message
+    -m, --mixer     sets the mixer to use (default='default')
+    -c, --control   sets the control to use (default='Master')
+    toggle          toggles between mute and unmute
+    up              increase the volume by the given %
+    down            decrease the volume by the given %
+    print           print the volume in a fancy format
+    i3blocks        use the script with i3blocks (left-click opens pavu-control, right-click will toggle the volume,
+                    scroll up will increase it, scroll down will decrease it)
+EOF
 }
 
-case "$BLOCK_BUTTON" in
-    1) set_default_playback_device_next ;;
-    2) amixer -q -D pulse sset Master toggle ;;
-    3) set_default_playback_device_next -1 ;;
-    4) amixer -q -D pulse sset Master 5%+ ;;
-    5) amixer -q -D pulse sset Master 5%- ;;
-esac
+get_mixer() {
+  if [ -n $MIXER ]
+  then
+    if [ -n "$(lsmod | grep pulse)" ]
+    then
+      MIXER="pulse"
+    elif [ -n "$(lsmod | grep jack)" ]
+    then
+      MIXER="jackplug"
+    else
+      MIXER="default"
+    fi
+  fi
 
-for name in INDEX NAME VOL MUTED; do
-	read $name
-done < <(pacmd list-sinks | grep "index:\|name:\|volume: front\|muted:" | grep -A3 '*')
-INDEX=$(echo "$INDEX" | grep -o '[0-9]\+')
-VOL=$(echo "$VOL" | grep -o "[0-9]*%" | head -1 )
-VOL="${VOL%?}"
-NAME=$(echo "$NAME" | sed 's/.*\.\(.*\)>/\1/')
-if [[ $MUTED =~ "no" ]] ; then
-	SYMBOL=$AUDIO_HIGH_SYMBOL
-    [[ $VOL -le $AUDIO_MED_THRESH ]] && SYMBOL=$AUDIO_MED_SYMBOL
-    [[ $VOL -le $AUDIO_LOW_THRESH ]] && SYMBOL=$AUDIO_LOW_SYMBOL
-    COLOR=$DEFAULT_COLOR
-else
-	SYMBOL=$AUDIO_MUTED_SYMBOL
-	COLOR=$MUTED_COLOR
-fi
-
-function print_format {
-    PERCENT="%"
-    [[ $USE_PERCENT == 0 ]] && PERCENT=""
-    case "$1" in
-        1) echo "$SYMBOL$VOL$PERCENT [$NAME]" ;;
-        2) echo "$SYMBOL$VOL$PERCENT [$INDEX]";;
-        3) echo "$SYMBOL$VOL$PERCENT" ;;
-        *) echo "$SYMBOL$VOL$PERCENT [$INDEX:$NAME]" ;;
-    esac
+  echo $MIXER
 }
 
-print_format "$LONG_FORMAT"
-print_format "$SHORT_FORMAT"
-echo "$COLOR"
+get_scontrol() {
+  if [ -n $SCONTROL ]
+  then
+    local mixer=$(get_mixer)
+    SCONTROL=$(amixer -D $mixer scontrols | sed -n "s/Simple mixer control '\([A-Za-z ]*\)',0/\1/p" | head -n1)
+  fi
+
+  echo $SCONTROL
+}
+
+get_capability() {
+  amixer -D $(get_mixer) get $(get_scontrol) | sed -n "s/  Capabilities:.*cvolume.*/Capture/p"
+}
+
+get_volume() {
+  amixer -D $(get_mixer) get $(get_scontrol) $(get_capability) | grep -o "\[.*%\]" | grep -o "[0-9]*" | head -n1
+}
+
+is_muted() {
+  amixer -D $(get_mixer) get $(get_scontrol) | grep -q "\[off\]"
+}
+
+toggle() {
+  amixer -q -D $(get_mixer) sset $(get_scontrol) $(get_capability) toggle
+}
+
+up() {
+  amixer -q -D $(get_mixer) sset $(get_scontrol) $(get_capability)  ${1:-"5"}+ unmute
+}
+
+down() {
+  amixer -q -D $(get_mixer) sset $(get_scontrol) $(get_capability)  ${1:-"5"}- unmute
+}
+
+icon() {
+  local volume=$(get_volume)
+  if [ "$volume" -le 25 ] || is_muted
+  then
+    echo $AUDIO_MUTED_SYMBOL
+  elif [ "$volume" -le 50 ]
+  then
+    echo $AUDIO_LOW_SYMBOL
+  else
+    echo $AUDIO_HIGH_SYMBOL
+  fi
+}
+
+print() {
+  local volume=$(get_volume)
+  local output=$(icon)
+  if [ "$volume" -eq 0 ] || is_muted
+  then
+    output="$output muted"
+  else
+    output="$output $volume%"
+  fi
+
+  echo $output
+}
+
+i3blocks() {
+  case "$BLOCK_BUTTON" in
+    1)
+      pavucontrol -t 3
+      ;;
+    3)
+      toggle
+      ;;
+    4)
+      up 5
+      ;;
+    5)
+      down 5
+      ;;
+  esac
+
+  print
+}
+
+main() {
+  if [[ -z $1 ]]
+  then
+    print
+  else
+    until [[ -z $1 ]]
+    do
+      case $1 in
+        -h|--help )
+          usage
+          exit 0
+          ;;
+        -m|--mixer )
+          shift
+          MIXER=$1
+          ;;
+        -c|--control )
+          shift
+          SCONTROL=$1
+          ;;
+        toggle )
+          toggle
+          ;;
+        up )
+          shift
+          up $1
+          ;;
+        down )
+          shift
+          down $1
+          ;;
+        print )
+          print
+          ;;
+        i3blocks )
+          i3blocks
+          ;;
+        * )
+          echo "Invalid option '$1'"
+          exit 1
+          ;;
+      esac
+      shift
+    done
+  fi
+}
+
+main $@
